const DATA = window.HXH_DATA;
const $ = (sel) => document.querySelector(sel);
const screens = {home:$("#homeScreen"),list:$("#listScreen"),detail:$("#detailScreen")};
const labels = {episodes:"話数",characters:"キャラクター",organizations:"組織",terms:"用語",storylines:"ストーリーライン",books:"単行本"};
const stateStack = ["home"];
function escapeHTML(str){return String(str||"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function imgFallback(src, cls, alt, book=false){const img=document.createElement("img");img.src=src;img.className=cls;img.alt=alt||"";img.onerror=()=>{img.onerror=null;const w=book?240:200,h=book?360:200;img.src="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${w} ${h}'><rect width='${w}' height='${h}' fill='#222'/><text x='${w/2}' y='${h/2-6}' fill='#fff' font-size='18' font-family='sans-serif' text-anchor='middle'>NO IMAGE</text><text x='${w/2}' y='${h/2+20}' fill='#aaa' font-size='12' font-family='sans-serif' text-anchor='middle'>${escapeHTML(alt)}</text></svg>`)};return img}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function typeIntro(){const targets=[...document.querySelectorAll(".type-target")];let delay=180;targets.forEach(el=>{const text=el.dataset.text||"";el.textContent="";[...text].forEach((ch,i)=>setTimeout(()=>el.textContent+=ch,delay+i*48));delay+=text.length*48+230});setTimeout(()=>$("#enterBtn").classList.add("show"),delay+350)}
function showScreen(name,push=true){Object.values(screens).forEach(s=>s.classList.add("hidden"));screens[name].classList.remove("hidden");if(push&&stateStack[stateStack.length-1]!==name)stateStack.push(name);window.scrollTo({top:0,behavior:"smooth"})}
function goBack(){if(stateStack.length>1)stateStack.pop();showScreen(stateStack[stateStack.length-1]||"home",false)}
function renderHome(){const chars=shuffle(DATA.characters);const charWrap=$("#characterMarquee");charWrap.innerHTML="";[...chars,...chars].forEach(c=>{const btn=document.createElement("button");btn.className="character-card";btn.appendChild(imgFallback(c.image,"character-avatar",c.name));const span=document.createElement("span");span.textContent=c.name;btn.appendChild(span);btn.onclick=()=>openDetail("characters",c);charWrap.appendChild(btn)});const bookWrap=$("#bookMarquee");bookWrap.innerHTML="";[...DATA.books,...DATA.books].forEach(b=>{const btn=document.createElement("button");btn.className="book-card";btn.appendChild(imgFallback(b.image,"book-cover",b.name,true));const strong=document.createElement("strong");strong.textContent=b.name;const range=document.createElement("span");range.textContent=b.range;const note=document.createElement("span");note.textContent=b.text.replace(/\n/g," / ");btn.append(strong,range,note);btn.onclick=()=>openDetail("books",b);bookWrap.appendChild(btn)});$("#latestTitle").textContent=`${DATA.meta.latest.episode}　${DATA.meta.latest.title}`;$("#latestThumb").style.backgroundImage=`url(${DATA.meta.latest.characterImage})`}
function listData(type){return DATA[type]||[]}
function openList(type){$("#listTitle").textContent=labels[type]||"一覧";const wrap=$("#listContent");wrap.innerHTML="";listData(type).forEach(item=>{const btn=document.createElement("button");btn.className="list-card";if(type==="characters"){btn.appendChild(imgFallback(item.image,"",item.name))}if(type==="books"){btn.appendChild(imgFallback(item.image,"book-mini",item.name,true))}const strong=document.createElement("strong");strong.textContent=item.name||item.title||item.no;const small=document.createElement("small");small.textContent=item.range||(item.text||item.profile||"").split("\n")[0]||"";btn.append(strong,small);btn.onclick=()=>openDetail(type,item);wrap.appendChild(btn)});showScreen("list")}
function openDetail(type,item){$("#detailKicker").textContent=(labels[type]||"DETAIL").toUpperCase();$("#detailTitle").textContent=item.name||item.title||item.no||"詳細";const detail=$("#detailContent");detail.innerHTML="";if(type==="characters"){const hero=document.createElement("div");hero.className="detail-hero";hero.appendChild(imgFallback(item.image,"",item.name));const title=document.createElement("h3");title.textContent=item.name;hero.appendChild(title);detail.appendChild(hero);const p=document.createElement("p");p.textContent=item.profile||"";detail.appendChild(p)}else if(type==="books"){const hero=document.createElement("div");hero.className="detail-hero";hero.appendChild(imgFallback(item.image,"book-detail",item.name,true));const title=document.createElement("h3");title.textContent=item.name;hero.appendChild(title);detail.appendChild(hero);const p=document.createElement("p");p.textContent=`${item.range}\n${item.text}`;detail.appendChild(p)}else{const p=document.createElement("p");p.textContent=item.text||item.summary||item.profile||"";detail.appendChild(p)}showScreen("detail")}
function performSearch(q){q=(q||"").trim();const results=$("#searchResults");if(!q){results.classList.add("hidden");results.innerHTML="";return}const hits=[];["episodes","characters","organizations","terms","storylines","books"].forEach(type=>{listData(type).forEach(item=>{if(JSON.stringify(item).includes(q))hits.push({type,item})})});results.classList.remove("hidden");results.innerHTML=`<h2>検索結果：${escapeHTML(q)}</h2>`;hits.slice(0,30).forEach(({type,item})=>{const div=document.createElement("button");div.className="list-card";div.style.width="100%";div.style.marginBottom="10px";const strong=document.createElement("strong");strong.textContent=item.name||item.title||item.no;const small=document.createElement("small");small.textContent=labels[type]||type;div.append(strong,small);div.onclick=()=>openDetail(type,item);results.appendChild(div)});if(!hits.length)results.innerHTML+=`<div class="list-card"><strong>該当なし</strong></div>`}
document.addEventListener("DOMContentLoaded",()=>{typeIntro();renderHome();$("#enterBtn").addEventListener("click",()=>{$("#intro").classList.add("hidden");$("#app").classList.remove("hidden")});document.querySelectorAll("[data-open-list]").forEach(btn=>btn.addEventListener("click",()=>openList(btn.dataset.openList)));document.querySelectorAll("[data-back]").forEach(btn=>btn.addEventListener("click",goBack));$("#searchInput").addEventListener("input",e=>performSearch(e.target.value))});
